### ISSUE TITLE
Unlocking faceid with foto from phone

### ISSUE THREAD

**Issue by TyomikJan** [xames3/FaceID#1]
Hello @xames3! I have downloaded your faceid model and I was quite excited. But when I made a photo of my face with my phone, and showed it to the camera I could unlock it too. This is unacceptable for the task I want it to perform. After this case during face scanning I was changing the position of my face all the time. But it neither helped. So I am writing to you to ask few questions. 
Technical Information:
Python version: 3.6.8 (64-bit)
Windows: 8.1 (64-bit)

IMPORTANT QUESTIONS:

- How to solve this problem?
- How should I keep my face during face scanning?

And two more questions( less importance):
- Does this model work with less lighting?
- Can I connect this app to a repository, instead of excel?

Thanks for your attention!

**Comment by stardust-xs** [comment]
**TRUE** Apologies, for not replying fast...

@TyomikJan, thanks for taking an interest into this project. As you might have noticed its fairly a deprecated code (it works but doesn't perform great) from today's standpoint. I can understand your request and if I'm not wrong, I think you're trying to build something like Apple's FaceID (wherein you can unlock). I'll be honest... Unfortunately, this type of technology is little difficult to implement with high-precision. We can build small packages (codes/microservices) to perform each of the required small tasks and then use its output at inference.

- How to solve this problem?
  - For ensuring the application doesn't allow bypassing via a photograph OR a phone or basically an 2D image, you need to implement something called as Liveliness Detection. (It's gets better with high test samples).
  - Using a Machine Learning model instead of Haar Cascades for better head/face pose handling (This will cover issues with side profile images). 

- How should I keep my face during face scanning?
  - Right now, if you're following along this code, try NOT to move and keep looking at your camera and rotate your face with minimal motion (move little slow) so that more NON-BLURRY frames could be captured.

- Does this model work with less lighting?
  - No. This is extremely basic implementation of face localization. I would urge you to go for ML based approaches preferably MTCNN (IMO).

- Can I connect this app to a repository, instead of excel?
  - Yes. Fork it and feel free to modify the code however you want. But try to implement proper/decent face detection/localization using ML based models and then go for this one.

**Note:** If you need any help, feel free to pop in your questions here. I'll share some easy reference links with you.

**Comment by TyomikJan** [comment]
Thanks for your reply, **@xames3**! You are right, I am trying to build something like Apple Face ID. 
I implemented liveness detection from this link: https://www.pyimagesearch.com/2019/03/11/liveness-detection-with-opencv/ and merged it with yours. I am going to slightly update it to combine it better. If you would like to help me, it would be great. I will make a repository in a few days.
Thank you very much again!

**Comment by stardust-xs** [comment]
@TyomikJan I would really love to contribute in your work. I was also going to implement something similar but because of some restriction within the technology, it was kinda stopping me from building this stuff. Count me in. I'll try to be helpful.

Closing this one.

**Comment by TyomikJan** [comment]
Awesome! Here is the repository: 
https://github.com/TyomikJan/Face-ID-with-liveness-detection
